import { integer, real, sqliteTable, text } from 'drizzle-orm/sqlite-core';

export const products = sqliteTable('products', {
  id: text('id').primaryKey(), sku: text('sku').notNull().unique(), name: text('name').notNull(), slug: text('slug').notNull().unique(), category: text('category').notNull(), otherCategory: text('other_category'), shortDescription: text('short_description').notNull(), fullDescription: text('full_description').notNull(), regularPrice: real('regular_price').notNull(), salePrice: real('sale_price'), mainImage: text('main_image').notNull(), additionalImages: text('additional_images_json').notNull().default('[]'), material: text('material').notNull(), dimensions: text('dimensions').notNull(), colours: text('colours_json').notNull().default('[]'), sizes: text('sizes_json').notNull().default('[]'), variants: text('variants_json').notNull().default('[]'), variantPricing: text('variant_pricing_json').notNull().default('{}'), customisable: integer('customisable',{mode:'boolean'}).notNull().default(false), customisationOptions: text('customisation_options_json').notNull().default('[]'), customisationCharge: real('customisation_charge').notNull().default(0), customisationNotes: text('customisation_notes').notNull().default(''), stockQuantity: integer('stock_quantity'), availability: text('availability').notNull(), madeToOrder: integer('made_to_order',{mode:'boolean'}).notNull().default(false), preparationTime: text('preparation_time').notNull(), careInstructions: text('care_instructions').notNull(), labels: text('labels_json').notNull().default('[]'), tags: text('tags_json').notNull().default('[]'), visibility: integer('visibility',{mode:'boolean'}).notNull().default(true), featured: integer('featured',{mode:'boolean'}).notNull().default(false), bestseller: integer('bestseller',{mode:'boolean'}).notNull().default(false), newArrival: integer('new_arrival',{mode:'boolean'}).notNull().default(false), createdAt: text('created_at').notNull(), updatedAt: text('updated_at').notNull()
});

export const orders = sqliteTable('orders', {
  id:text('id').primaryKey(), timestamp:text('timestamp').notNull(), customerName:text('customer_name').notNull(), email:text('email').notNull(), phone:text('phone').notNull(), addressJson:text('address_json').notNull(), itemsJson:text('items_json').notNull(), variantsJson:text('variants_json').notNull(), personalisationJson:text('personalisation_json').notNull(), subtotal:real('subtotal').notNull(), discount:real('discount').notNull().default(0), shippingCharge:real('shipping_charge'), total:real('total').notNull(), paymentMethod:text('payment_method').notNull(), paymentStatus:text('payment_status').notNull(), orderStatus:text('order_status').notNull(), trackingNumber:text('tracking_number'), notes:text('notes')
});

export const customRequests = sqliteTable('custom_requests', {
  id:text('id').primaryKey(), timestamp:text('timestamp').notNull(), name:text('name').notNull(), email:text('email').notNull(), phone:text('phone').notNull(), occasion:text('occasion'), productType:text('product_type'), budget:real('budget'), requiredBy:text('required_by'), details:text('details').notNull(), coloursTheme:text('colours_theme'), quantity:integer('quantity').notNull().default(1), giftMessage:text('gift_message'), referenceImageKey:text('reference_image_key'), notes:text('notes'), status:text('status').notNull().default('RECEIVED')
});

export const contacts = sqliteTable('contacts', {
  id:text('id').primaryKey(), timestamp:text('timestamp').notNull(), name:text('name').notNull(), email:text('email').notNull(), phone:text('phone'), subject:text('subject').notNull(), message:text('message').notNull(), status:text('status').notNull().default('NEW')
});
